### ISSUE TITLE
Add support for image auto-orientation

### ISSUE THREAD

**Issue by jnicklas** [refile/refile-mini_magick#1]
See refile/refile#79

**Comment by janko** [comment]
Ok, let's continue the dicussion here.

@danieldraper, I think the auto-orient feature isn't something that should be there by default, because I would expect that if the image is rotated during uploading, that it stays that way after upload. I think we shouldn't alter images in any way, except the size in this case.

Similar to @lazaronixon's advice, I would recommend if you want this to be default behaviour, to do something like this:

``` rb
Refile::MiniMagick.prepend Module.new {
  [:limit, :fit, :fill, :pad].each do |action|
    define_method(action) do |img, *args|
      super(img, *args) { |cmd| cmd.auto_orient }
    end
  end
}
```

Otherwise you can subclass `Refile::MiniMagick` like @lazaronixon suggested, which is probably a more idiomatic approach. For me it really makes sense to just use subclassing to achieve this, or make your own processor if you want something more custom.

Adding some configuration option to Refile which you could give a block which yields the image object is something I thought about, but I think it broadens the API making it more unstable. For example, I recently had to change refile-mini_magick to use `convert` instead of `mogrify` to make it working with GraphicsMagick, and then yielding `MiniMagick::Tool::Convert` instead of `MiniMagick::Tool::Mogrify` could break someone's code. Just for an example.

I would consider this solved, @jnicklas?

**Comment by mtrolle** [comment]
@janko-m where would I put your code?
I tried creating config/initializers/refile.rb and paste your code here, but that just failed with `uninitialized constant Refile::MiniMagick`

**Comment by janko** [comment]
Try `require "refile/mini_magick"` (and make sure you have `refile-mini_magick` in the Gemfile).

**Comment by mtrolle** [comment]
Thanks @janko-m - I didn't realize you had separated this so I was still using old image processing. Didn't need to require once I got the right Gem ;)

However I did have do change your `super` line to:
`super(img, *args)`

**Comment by janko** [comment]
Aha, yes, you have to do that with `define_method`. I will corrected this now for future users.

**Comment by ctro** [comment]
Came here to say thanks @janko-m! the code snippet above solved my auto-rotation problems.

**Comment by grosser** [comment]
Can we have the 'expected' / 'right' behavior by default please ?
- image shows correctly oriented in standalone tab
- image shows correctly oriented in Preview
- image shows correctly oriented in other photo apps

... just not in the browser ... seems to be a common problem ... found a bunch of stackoverflow posts before I came here ... maybe make it disable-able ?
(I'll do the PR if that's acceptable ... alternatively a simple flag to turn auto_orient on ... but preferably 'correct' by default would be great and save lot's of people the search for the solution to this issue)

**Comment by lsarni** [comment]
[This comment](https://github.com/janko-m/image_processing/issues/7#issuecomment-374700962) on #7 means that @janko-m code on his first comment is no longer necessary, right?

**Comment by janko** [comment]
Yes, that is correct, given that you're pulling refile-mini_magick from `master` (as I don't think the switch to image_processing has been released yet).
